# Generated by Django 2.2.1 on 2019-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('position', models.TextField()),
            ],
        ),
    ]
