# Generated by Django 2.2.1 on 2019-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('H', '힙합'), ('B', '벌러두'), ('D', '댄스')], max_length=20)),
                ('lylics', models.TextField()),
            ],
        ),
    ]
