# Generated by Django 2.2.1 on 2019-05-18 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('w6app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='lylics',
            new_name='lyrics',
        ),
        migrations.AddField(
            model_name='playlist',
            name='composer',
            field=models.CharField(default='작사가없음', max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='lyricist',
            field=models.CharField(default='작곡가없음', max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='release',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
