# Generated by Django 2.2.1 on 2019-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categorys', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('categorys', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('info', models.TextField()),
            ],
        ),
    ]
