# Generated by Django 2.2.1 on 2019-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericainfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exid',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
