# Generated by Django 2.2.1 on 2019-07-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ericainfo', '0003_auto_20190718_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categorys',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericainfo.Category'),
        ),
    ]
